#ifndef PSYSTEMCONSTANTS_H
#define PSYSTEMCONSTANTS_H

#define PI 3.1415f
#define POLY6_CONST 1.5666814f
#define SPIKY_CONST 14.323944f

#define PARTICLE_H   2.0f
#define PARTICLE_H2  (PARTICLE_H * PARTICLE_H)
#define PARTICLE_H3  (PARTICLE_H2 * PARTICLE_H)
#define PARTICLE_H4  (PARTICLE_H2 * PARTICLE_H2)
#define PARTICLE_H6  (PARTICLE_H3 * PARTICLE_H3)
#define PARTICLE_H9  (PARTICLE_H6 * PARTICLE_H3)

#define PARTICLE_R 1.0f

#define MAX_NEIGHBOURS 32

#endif